# Generated by Django 5.2.8 on 2025-11-18 23:50

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adocato", "0004_gato_foto_alter_gato_nome"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("nome", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="gato",
            options={
                "ordering": ["nome"],
                "verbose_name": "Gato",
                "verbose_name_plural": "Gatos",
            },
        ),
        migrations.CreateModel(
            name="Adotante",
            fields=[
                (
                    "usuario_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="adocato.usuario",
                    ),
                ),
                ("telefone", models.CharField(max_length=15)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="adotantes/"),
                ),
            ],
            options={
                "verbose_name": "Adotante",
                "verbose_name_plural": "Adotantes",
            },
            bases=("adocato.usuario",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Coordenador",
            fields=[
                (
                    "usuario_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="adocato.usuario",
                    ),
                ),
                ("apelido", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Coordenador",
                "verbose_name_plural": "Coordenadores",
            },
            bases=("adocato.usuario",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Solicitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criadaEM", models.DateTimeField(auto_now_add=True)),
                ("recurso", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ANALISE", "Em Análise"),
                            ("APROVADA", "Aprovada"),
                            ("REPROVADA", "Reprovada"),
                            ("EM_RECURSO", "Em Recurso"),
                        ],
                        default="EM_ANALISE",
                        max_length=20,
                    ),
                ),
                (
                    "gato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitacoes",
                        to="adocato.gato",
                    ),
                ),
                (
                    "adotante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitacoes",
                        to="adocato.adotante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação",
                "verbose_name_plural": "Solicitações",
                "ordering": ["-criadaEM"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="documentos/")),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                ("enviadoEM", models.DateTimeField(auto_now_add=True)),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="adocato.solicitacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-enviadoEM"],
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parecer", models.TextField(blank=True, null=True)),
                ("dataAvaliacao", models.DateTimeField(auto_now_add=True)),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adocato.solicitacao",
                    ),
                ),
                (
                    "coordenador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adocato.coordenador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "ordering": ["-dataAvaliacao"],
            },
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="avaliadores",
            field=models.ManyToManyField(
                blank=True,
                related_name="avaliacoes",
                through="adocato.Avaliacao",
                to="adocato.coordenador",
            ),
        ),
    ]
