# Generated by Django 5.2.7 on 2025-11-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocato', '0005_usuario_alter_gato_options_adotante_coordenador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adotante',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
